api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from api.register import RegisterViewSet
from api.bijuterii import BijuterieViewSet

router = DefaultRouter()
router.register(r'register', RegisterViewSet, basename='register')
router.register(r'bijuterii', BijuterieViewSet)


urlpatterns=[
    path('', include(router.urls)),
    path('browser-auth', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

bijuterii/urls.py
from django.urls import path
from django.core.paginator import  Paginator
from bijuterii.views import show_all_bijuterii, show_bijuterie_details, add_bijuterie_to_cart, show_checkout, remove_bijuterie_from_cart


app_name='bijuterii'

urlpatterns = [
    path ('', show_all_bijuterii, name='all' ) ,
    path ('<int:bijuterie_id>/' , show_bijuterie_details , name='details'),
    path('<int:bijuterie_id>/add_to_cart', add_bijuterie_to_cart, name='add_to_cart'),
    path('checkout/', show_checkout, name='checkout'),
    path('<int:bijuterie_id>/remove_from_cart/', remove_bijuterie_from_cart, name='remove_from_cart'),
]

finessa/urls.py
from django.contrib import admin
from django.urls import path, include
from finessa.views import homepage_view

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from finessa.views import homepage_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view),
    path ('bijuterii/' , include('bijuterii.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bijuterii/models.py
from django.db import models

from django.contrib.auth import get_user_model

AuthUserModel = get_user_model()

class Culoareaur(models.Model):
    name = models.CharField(max_length=128, null=False)

class Bijuterie(models.Model):
    name = models.CharField(max_length=128, null=False)
    # producty_type = models.CharField(max_length= 15, null=False)
    # product = models.ForeignKey(Bijuterie, on_delete=models.CASCADE)
    culoriaur = models.ManyToManyField(Culoareaur, through='BijuterieCuloareaur')
    quantity = models.IntegerField(default=0, null=False)
    price = models.DecimalField(max_digits=8, decimal_places=2) # minȘ 0.00
    color_gold = models.CharField(max_length=10, null=False)
    greutate = models.DecimalField(max_digits=4, decimal_places=2)
    size = models.IntegerField( default=0 , null=False )
    # image = models.ImageField

    def __str__(self):
        return f'<Bijuterie object ID = {self.name}>'

class BijuterieCuloareaur(models.Model):
    bijuterie = models.ForeignKey(Bijuterie, on_delete=models.CASCADE, related_name='categories_pivot')  # product.categories[0].category.name
    culoareaur = models.ForeignKey(Culoareaur, on_delete=models.CASCADE, related_name='bijuterii_pivot')  # category.products[0].product.name
    extra_column = models.IntegerField(null=True, default=None)

users/models/details.py
from django.db import models
from django.conf import settings
from django.templatetags.static import static
from django.utils import timezone
from utils.constants.activation import ACTIVATION_DICT


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='profile_images/', null=True, default=None)

    @property
    def image(self):
        if self.avatar:
            return self.avatar.url

        return static('images/defaultUser.jpg')


class Activation(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activation')
    token = models.CharField(max_length=64, null=True, default=None, blank=False, unique=True)
    expires_at = models.DateTimeField(default=timezone.now() + timezone.timedelta(**ACTIVATION_DICT))
    activated_at = models.DateTimeField(null=True, default=None, blank=False)

    def __str__(self):
        return self.token

    def __repr__(self):
        return self.token


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')  # user.cart
    data = models.JSONField()

bijuterii/forms.py
from django import forms
from bijuterii.models import Culoareaur, Bijuterie
# from payments.models import StripeCard

ORDER_BY_CHOICES = (('POPULARITY', 'Popularity'), ('PRICE_ASC', 'Price ascending'), ('PRICE_DESC', 'Price descending'))


def get_orderby_field(order_by):
    if order_by == 'PRICE_ASC':
        return 'price'

    if order_by == 'PRICE_DESC':
        return '-price'

    return 'id'


class FilterBijuterieForm(forms.Form):
    order_by = forms.ChoiceField(choices=ORDER_BY_CHOICES)
    culoriaur = forms.MultipleChoiceField(choices=(), widget=forms.CheckboxSelectMultiple, required=False)
    min_price = forms.DecimalField(max_digits=5, decimal_places=2, required=False)
    max_price = forms.DecimalField(max_digits=5, decimal_places=2, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        culoriaur = Culoareaur.objects.all()
        self.fields['culoriaur'].choices = tuple((culoareaur.id, culoareaur.name) for culoareaur in culoriaur)

    def clean_culoriaur(self):
        culoriaur = self.cleaned_data.get('culoriaur', [])
        return culoriaur

    def apply_filters(self):
        is_valid = self.is_valid()

        if is_valid:
            order_by = get_orderby_field(self.cleaned_data.get('order_by'))
            culoriaur = self.cleaned_data.get('culoriaur', [])
            min_price = self.cleaned_data.get('min_price')
            max_price = self.cleaned_data.get('max_price')
            #
            # print('culoriaur', culoriaur)
            # print('min_price', type(min_price))
            # print('max_price', type(max_price))

            bijuterii = Bijuterie.objects.order_by(order_by)

            if len(culoriaur) > 0:
                bijuterii = bijuterii.filter(culoriaur__id__in=culoriaur)

            if min_price:
                bijuterii = bijuterii.filter(price__gte=min_price)

            if max_price:
                bijuterii = bijuterii.filter(price__lte=max_price)

            return bijuterii

        return Bijuterie.objects.all()


class SelectCardForm(forms.Form):
    card = forms.ChoiceField(choices=(), widget=forms.RadioSelect)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._user = user

        self.fields['card'].choices = tuple((card.id, card.number) for card in self._user.stripe_customer.cards.all())

    # def clean_card(self):
    #     card_id = self.cleaned_data['card']
    #
    #     try:
    #         card = StripeCard.objects.get(id=card_id)
    #     except StripeCard.DoesNotExist:
    #         card = None
    #
    #     if card is None:
    #         raise forms.ValidationError('Selected card is invalid.')
    #
    #     if card.stripe_customer.user.id != self._user.id:
    #         raise forms.ValidationError('Selected card is invalid.')
    #
    #     return card
    #

bijuterii/views.py
from django.shortcuts import render, get_object_or_404, Http404, redirect, reverse
from django.core.paginator import Paginator
from bijuterii.models import Bijuterie
from bijuterii.forms import FilterBijuterieForm, SelectCardForm
from utils.cart.cart import Cart


def show_all_bijuterii(request):
    print('request.GET', request.GET)
    form = FilterBijuterieForm(data=request.GET)
    bijuterii = form.apply_filters()

    paginator = Paginator(bijuterii, 4)
    page_obj = paginator.get_page(request.GET.get('page', 1))

    return render(request, 'bijuterii/bijuterii.html', {
        'page_obj': page_obj,
        # 'form': form,
        'form': FilterBijuterieForm()
    })


def show_bijuterie_details(request, bijuterie_id):

    bijuterie = get_object_or_404(Bijuterie, pk=bijuterie_id)

    return render(request, 'bijuterii/details.html', {
        'bijuterie': bijuterie,
    })


def add_bijuterie_to_cart(request, bijuterie_id):
    bijuterie = get_object_or_404(Bijuterie, id=bijuterie_id)
    quantity = request.POST.get('quantity')

    try:
        quantity = int(quantity)
    except (ValueError, TypeError):
        raise Http404('Quantity attribute is not valid.')

    cart = Cart(request)
    cart.add(bijuterie_id, quantity)

    return redirect(reverse('bijuterii:all'))


def show_checkout(request):
    cart = request.session.get('cart', {})
    bijuterii = Bijuterie.objects.filter(id__in=cart.keys())

    cart_items = [
        {
            "bijuterie": bijuterie,
            "quantity": cart[str(bijuterie.id)],
            "total": '%.2f' % (float(bijuterie.price) * int(cart[str(bijuterie.id)]))
        }
        for bijuterie in bijuterii
    ]

    return render(request, 'bijuterii/checkout.html', {
        'cart_items': cart_items,
        'cart': cart,
    })


def remove_bijuterie_from_cart(request, bijuterie_id):
    get_object_or_404(Bijuterie, pk=bijuterie_id)

    cart = Cart(request)
    cart.remove(bijuterie_id)

    return redirect(reverse('bijuterii:checkout'))

bijuterii/templates/bijuterii/bijuterii.html
{% extends 'base.html'%}


{% block title %}
    <title>Bijuterii Page</title>
{% endblock %}

{% block content %}
    <div class="row">
    <div class = "col-12 col-m-6">
<!--        <h1>Bijuterii</h1>-->
        <h1>Bijuterii {{ request.session.cart }}</h1>
        </div>
    </div>
        <div class = 'row'>
            <div class="col-12">
                <form method="get" action="{% url 'bijuterii:all' %}">
                    {{ form.as_p }}
                    <input type="submit" value="Apply filters"/>
                </form>
            </div>
        </div>
      <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


    <ul class="row">
        {% for bijuterie in page_obj %}
        <li style="margin-bottom: 10px;" class="col-12 col-md-6">
        <div>

            {{bijuterie.name}} - {{bijuterie.price}} RON <a href="{% url 'bijuterii:details' bijuterie.id %}">Vezi bijuterie</a>

        </div>
            <div>
                <form method="post" action="{% url 'bijuterii:add_to_cart' bijuterie.id %}">
                    {% csrf_token %}
<!--                    <input type = "hidden" value="{{bijuterie.id}}" name="bijuterie_id" />-->
                    <input type = "number" value="0" name="quantity" />
                    <input type = "submit" value="Add to cart" />

                </form>
            </div>
        </li>
    {% endfor %}
        </ul>
    </ul>
{% endblock %}

bijuterii/templates/bijuterii/details.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ bijuterie.name }}</title>
{% endblock %}

{% block content %}
    <div class="container">
        <p><strong>Name:</strong> {{ bijuterie.name }}</p>
        <p><strong>Price:</strong> {{ bijuterie.price }} RON</p>
<!--        <p><strong>Store:</strong> {{ bijuterie.store.name }}</p>-->
<!--        <p><strong>Store Owner:</strong> {{ bijuterie.store.owner.username }}</p>-->
        <p><strong>Culoare aur</strong></p>
        <ul>
            {% for culoareaur in bijuterie.culoriaur.all %}
                <li>{{ culoareaur.name }} </li> #({{ culoareaur.extra_column }})
            {% endfor %}
        </ul>
        {% comment %}
        <ul>
            {% for culoareaur_pivot in bijuterie.culoriaur_pivot.all %}
                <li>{{ culoareaur_pivot.culoareaur.name }}</li>  # ({{ culoareaur_pivot.extra_column }})
            {% endfor %}
        </ul>
        {% endcomment %}
    </div>
{% endblock %}