api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from api.register import RegisterViewSet
from api.bijuterii import BijuterieViewSet

router = DefaultRouter()
router.register(r'register', RegisterViewSet, basename='register')
router.register(r'bijuterii', BijuterieViewSet)


urlpatterns=[
    path('', include(router.urls)),
    path('browser-auth', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

bijuterii/urls.py
from django.urls import path
from django.core.paginator import  Paginator
from bijuterii.views import show_all_bijuterii, show_bijuterie_details, add_bijuterie_to_cart, show_checkout, remove_bijuterie_from_cart


app_name='bijuterii'

urlpatterns = [
    path ('', show_all_bijuterii, name='all' ) ,
    path ('<int:bijuterie_id>/' , show_bijuterie_details , name='details'),
    path('<int:bijuterie_id>/add_to_cart', add_bijuterie_to_cart, name='add_to_cart'),
    path('checkout/', show_checkout, name='checkout'),
    path('<int:bijuterie_id>/remove_from_cart/', remove_bijuterie_from_cart, name='remove_from_cart'),
]

finessa/urls.py
from django.contrib import admin
from django.urls import path, include
from finessa.views import homepage_view

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from finessa.views import homepage_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view),
    path ('bijuterii/' , include('bijuterii.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login_user, register_user, logout_user, show_profile, activate

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register_user, name='register'),
    path('profile/', show_profile, name='profile'),
    path('activate/<str:token>/', activate, name='activate'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    {% endblock %}

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% block styles %}
    {% endblock %}


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'menu.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/homepage.html
<html>
{% load static %}
<head>
    <body>
<nav>
{% include 'menu.html' %}
        {% block styles %}
<!--    <link rel="stylesheet" href="{% static 'styles/homepage.css' %}"/>-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% endblock %}
</nav>
<h1>
    <img src="{% static 'images/Logo Mucea Roxana1v1.png' %}" width="375"/>
<!--    <span> Bijuteria Finessa </span>-->
</h1>
<h1>You are gold</h1>
</body>
</head>
</html>

templates/menu.html
{% load cart %}

<div class="container">
<nav>
        <a href="/"><button type="button" class="btn btn-light">BIJUTERIA FINESSA</button></a>

        <a href="{% url 'bijuterii:all' %}"> <button type="button" class="btn btn-outline-dark">BIJUTERII</button> </a>

         {% if request.user.is_authenticated %}

         <a href="">
                        {% comment %}
                            Cart ({{ request.session|bijuterie_no }})
                        {% endcomment %}

                        Cart ({{ request.session|dict_length:'cart' }})
                    </a>
        <a href="{% url 'users:profile' %}"><button type="button" class="btn btn-light">PROFILE</button></a>
        <a href="{% url 'users:logout' %}"><button type="button" class="btn btn-light">LOGOUT</button></a>

                {% else %}

        <a href="{% url 'users:login' %}"><button type="button" class="btn btn-light">LOGIN</button></a>
        <a href="{% url 'users:register' %}"><button type="button" class="btn btn-light">REGISTER</button></a>
         {% endif %}




</nav>
    </div>